name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust based on your project

      - name: Run tests
        run: pytest  # Adjust based on your test framework

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3
        with:
          heroku_api_key: $HRKU-1cecc10a-a7c9-466f-a9f4-1d33e13d07e8
          heroku_app_name: aap.py
